obs_dim: null  # inferred at runtime
n_actions: null

buffer_size: 100000
batch_size: 256
gamma: 0.99
target_entropy: 0.9

lr: 0.001
lr_alpha: 0.001 #alpha is just used for sampling, not for learning, so we can use a higher learning rate. 
optimizer: adam

subtract_min: false 
alpha_init: 0.1
learn_alpha: true

loss_weights:
    value_regret: 1.0
    regret: 1.0 #let's try to not use this at all, see if it still works. 
    value_regularization: 0.0001

#observation: using a positivity transform on the output leads to severe overestimation
positivity_transform: softplus #softplus, relu, exp, abs, square, identity

terminal_value: 0.0 # a smaller value than 0 rewards longer trajectories, this is an injected reward at terminal states
